; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s12
Gui Add, Text, x120 y16 w386 h23 +0x200, Selecciona la macro que deseas ejecutar
Gui Font
Gui Font, s11
Gui Add, ListBox, x40 y112 w214 h158, @Driano|Contraseñas|Ministerio
Gui Font
Gui Add, Button, x264 y320 w80 h23, & Ejecutar
Gui Add, Edit, x400 y184 w120 h21
Gui Add, Text, x320 y184 w65 h23 +0x200, Teléfono
Gui Add, Edit, x400 y224 w120 h21
Gui Add, Text, x320 y224 w72 h23 +0x200, Contraseña
Gui Add, CheckBox, x400 y136 w38 h23, Sí
Gui Add, CheckBox, x456 y136 w40 h23, No
Gui Font, s11
Gui Add, Text, x296 y104 w300 h23 +0x200, ¿Tiene teléfono en campo Remedy?
Gui Font

Gui Show, w620 h420, Window
Return

GuiEscape:
GuiClose:
    ExitApp
