; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
#MaxHotkeysPerInterval 99000000
#HotkeyInterval 99000000
#KeyHistory 0
ListLines Off
Process, Priority, , A
SetBatchLines, -1
SetKeyDelay, -1, -1
SetMouseDelay, -1
SetDefaultMouseSpeed, 0
SetWinDelay, -1
SetControlDelay, -1
SendMode Input
DllCall("ntdll\ZwSetTimerResolution","Int",5000,"Int",1,"Int*",MyCurrentTimerResolution)
SetWorkingDir, %A_ScriptDir%

Gui Add, Button, x328 y128 w136 h45 gButton1, Expediente digital
Gui Add, Button, x72 y72 w117 h43 gButton2, Adriano
Gui Add, Button, x544 y120 w112 h47 gButton3, Lexnet
Gui Add, Button, x248 y440 w158 h40 gButton4, GDU
Gui Add, Button, x72 y128 w117 h47 gButton5, Portafirmas NG
Gui Add, Button, x328 y72 w131 h41 gButton6, Arconte
Gui Add, Button, x200 y184 w119 h41 gButton7, Jara
Gui Add, Button, x960 y320 w115 h39 gButton8, @Driano
Gui Add, Button, x760 y160 w131 h46 gButton9, GM
Gui Add, Button, x200 y72 w116 h42 gButton10, Escritorio judicial
Gui Add, Button, x72 y184 w118 h44 gButton11, Hermes
Gui Add, Button, x760 y208 w133 h43 gButton12, Teléfono
Gui Add, Button, x200 y128 w119 h46 gButton13, Agenda de señalamientos
Gui Add, Button, x328 y184 w136 h41 gButton14, QUENDA // CITA PREVIA
Gui Add, Button, x544 y64 w112 h48 gButton15, ORFILA
Gui Add, Button, x960 y368 w116 h33 gButton16, PNJ
Gui Add, Button, x760 y56 w136 h47 gButton17, Lector  Tarjeta
Gui Add, Button, x760 y112 w136 h40 gButton18, Equipo sin red
Gui Font, s11
Gui Add, Text, x968 y24 w120 h23 +0x200, Contraseñas
Gui Font
Gui Add, Button, x968 y72 w104 h36 gButton19, AD
Gui Add, Button, x968 y120 w105 h34 gButton20, Correo
Gui Add, Button, x968 y168 w107 h40 gButton21, Temis
Gui Font, s11
Gui Add, Text, x800 y24 w120 h23 +0x200, DP
Gui Font
Gui Font, s11
Gui Add, Text, x984 y288 w122 h25 +0x200, Transfer
Gui Font
Gui Add, Button, x968 y224 w109 h43 gButton22, Arconte pass
Gui Font, s12
Gui Add, Text, x584 y240 w120 h23 +0x200, CAU
Gui Font
Gui Font, s11
Gui Add, Text, x560 y32 w120 h23 +0x200, Ministerio
Gui Font
Gui Add, Button, x760 y256 w134 h44 gButton23, Ganes
Gui Add, Button, x544 y176 w112 h44 gButton24, SIRAJ 2
Gui Add, Button, x528 y319 w155 h44 gButton25, Certificado digital
Gui Add, Button, x528 y272 w154 h43 gButton26, Emparejamiento ISL
Gui Font, s11
Gui Add, Text, x208 y24 w120 h23 +0x200, INCIDENCIAS
Gui Font
Gui Add, Button, x760 y312 w134 h43 gButton27, Equipo no enciende
Gui Add, Button, x104 y344 w136 h39 gButton28, Internet libre
Gui Add, Button, x104 y440 w138 h40 gButton29, ABBYPDF
Gui Add, Button, x104 y392 w136 h39 gButton30, DRAGON SPEAKING
Gui Font, s11
Gui Add, Text, x192 y304 w120 h23 +0x200, SOLICITUDES
Gui Font
Gui Add, Button, x248 y344 w158 h39 gButton31, MULTICONFERENCIA
Gui Add, Button, x248 y392 w159 h39 gButton32, Aumento espacio correos
Gui Add, Button, x528 y400 w149 h44 gButton33, Software
Gui Font, s11
Gui Add, Text, x568 y368 w120 h23 +0x200, Cierres
Gui Font
Gui Add, Button, x760 y360 w133 h49 gButton34, Disco duro
Gui Add, Button, x184 y240 w150 h40 gButton35, SUMINISTROS
Gui Font, s11, Verdana
Gui Add, Text, x928 y537 w195 h42 +0x200, Creado por David 🌙
Gui Font
Gui Add, Edit, x200 y512 w120 h21
Gui Add, Edit, x200 y544 w120 h21
Gui Add, Text, x160 y512 w34 h23 +0x200, DNI
Gui Font, s11
Gui Add, Text, x976 y424 w120 h23 +0x200, Teléfonos
Gui Font
Gui Add, Button, x528 y448 w150 h48, PIN TARJETA
Gui Font, s10
Gui Add, Text, x912 y464 w223 h23 +0x200, MINISTERIO - 913 859 800
Gui Font
Gui Font, s11
Gui Add, Text, x936 y496 w159 h23 +0x200, PNJ - 918 382 680
Gui Font
Gui Add, Button, x760 y416 w135 h47 gButton36, EDOC FORTUNY
Gui Font, s10
Gui Add, Text, x128 y544 w66 h25 +0x200, Teléfono
Gui Font
Gui Show, w1143 h595, CAU

;Variables 

screen()
{
    SetTitleMatchMode, 2
    WinActivate, ahk_class ArFrame
    Return
}

Alba(num)
{
    RunWait, powershell.exe -ExecutionPolicy Bypass -File "C:\Users\CAU.LAP\AppData\Roaming\AR System\HOME\ARCmds\Alba.ps1",, Hide
    screen()
    Send, ^i 
    Send, {TAB 2}{End}{Up %num%}{Enter}
    Send, {TAB 22}
    Return
}

;Lógica botones

Button1:
    Alba(20)
Return

Button2:
    Alba(33)
Return

Button3:
    Alba(13)
Return

Button4:
    Alba(18)
Return

Button5:
    Alba(9)
Return

Button6:
    Alba(30)
Return

Button7:
    Alba(14)
Return

Button8:
    Alba(12)
Return

Button9:
    Alba(17)
Return

Button10:
    Alba(21)
Return

Button11:
    Alba(16)
Return

Button12:
    Alba(2)
Return

Button13:
    Alba(32)
Return

Button14:
    Alba(8)
Return

Button15:
    Alba(11)
Return

Button16:
    Alba(10)
Return

Button17:
    Alba(3)
Return

Button18:
    Alba(7)
Return

Button19:
    Alba(34)
Return

Button20:
    Alba(27)
Return

Button21:
    Alba(1)
Return

Button22:
    Alba(30)
Return

Button23:
    Alba(19)
Return

Button24:
    Alba(6)
Return

Button25:
    Alba(28)
Return

Button26:
    Alba(23)
Return

Button27:
    Alba(22)
Return

Button28:
    Alba(15)
Return

Button29:
    Alba(35)
Return

Button30:
    Alba(25)
Return

Button31:
    Alba(0)
Return

Button32:
    Alba(31)
Return

Button33:
    Alba(5)
Return

Button34:
    Alba(26)
Return

Button35:
    Alba(4)
Return

Button36:
    Alba(24)
Return

#1::
    Alba(0)
Return

#9::
Send, {F3}{Enter}{Tab 5}
Return

#0::Reload
Return
XButton1::
Return

XButton2::
screen()
Send, #+s
Return

Return

GuiEscape:
GuiClose:
ExitApp
