// ods_data.js - generated 2026-06-23 14:52
// Source: Asignaciones Nuevo Adriano V7.04.ods (93 entries)
'use strict';

const ODS_CASOS = [
  {caso:'1', desc:'NUMERADORES ( RESOLUCIONES: AUTOS, SENTENCIAS Y DECRETOS ) -SALTO-', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error numerador resolución (Caso 1)', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'MT- Numeradores', enlaces:'https://videos.justicia.junta-andalucia.es/w/1SQQik3gDF3gP6B2Sq5uqr; https://videos.justicia.junta-andalucia.es/w/rvPBPz1xCnapmKENS3dpmk; https://videos.justicia.junta-andalucia.es/w/4sGqjGvCheqduBVZ2SsvVN'},
  {caso:'1.1', desc:'NUMERADORES ( RESOLUCIONES: AUTOS, SENTENCIAS Y DECRETOSNO NOTIFICADOS)YA ASIGNADOS - RENUMERACION-REAJUSTE', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error numerador resolución-ya asignado-(Caso 1.1)', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'MT- Numeradores', enlaces:'https://videos.justicia.junta-andalucia.es/w/1SQQik3gDF3gP6B2Sq5uqr; https://videos.justicia.junta-andalucia.es/w/rvPBPz1xCnapmKENS3dpmk;https://videos.justicia.junta-andalucia.es/w/4sGqjGvCheqduBVZ2SsvVN'},
  {caso:'2', desc:'NUMERADORES REGISTRO GENERAL / PRODECIMIENTOS INCOADOS', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error numerador reg. general (Caso 2)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Numeradores', enlaces:''},
  {caso:'2.1', desc:'NUMERADORES DE PROCEDIMIENTO INCOADO (SIN TOCAR REGISTRO GENERAL)', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error numerador procedimiento (Caso 2.1)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Numeradores', enlaces:''},
  {caso:'3', desc:'NUMERADORES REGISTRO GENERAL / PRODECIMIENTOS NO INCOADOS', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error numerador reg. general -no incoados (Caso 3)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Numeradores', enlaces:''},
  {caso:'4', desc:'NUMERADORES RESTO', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Numeradores resto (Caso 4)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Numeradores', enlaces:''},
  {caso:'5', desc:'SOPORTE FORMATIVO ATESTADOS / REPLICAS', clase:'SOPORTE FORMATIVO', tipo:'"ADRIANO"', cat:'ASESORAMIENTO/ | RECICLAJE', grupoPre:'', nivelCSU:'Formación', agrupacion:'', enlaces:'https://videos.justicia.junta-andalucia.es/w/skAUxXzqowHxnSwQWRCxag'},
  {caso:'6', desc:'DESBLOQUEOS RESTO: Error bloqueante,no puede trabajar sobre el procedimiento, No es 6.1 a 6.4.', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error trámite bloqueante (Caso 6)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT-Desbloqueo', enlaces:'https://videos.justicia.junta-andalucia.es/w/5xutwHVpoAbdjNJ7m7udyY'},
  {caso:'6.1', desc:'DESBLOQUEO DE EXPEDIENTE POR ACUMULACIÓN – Error por desacumulación (NO PUEDE HACER DACU)', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'', grupoPre:'', nivelCSU:'Servicios DevOps (si han ejecutado DACU en padre y sigue bloqueado)', agrupacion:'MT-Desbloqueo', enlaces:''},
  {caso:'6.2', desc:'DESBLOQUEO DE EXPEDIENTE POR MOTIVO DE ESTADO ARCHIVO BLOQUEANTE - Error por cambio de estado a terminado por acumulación o por transformación en otro procedimiento', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Desbloquear procedimiento archivado (Caso 6.2)', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'MT-Desbloqueo (error usuario)', enlaces:''},
  {caso:'6.3', desc:'DESBLOQUEO DE EXPEDIENTE POR MOTIVO DE ITINERACIÓN/ENJUICIAMIENTO', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Desbloquear procedimiento itineración. (Caso 6.3)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT-Desbloqueo (error de usuario)', enlaces:''},
  {caso:'6.4', desc:'DESBLOQUEO DE EXPEDIENTE POR TRANSFORMACIÓN DEL PROCEDIMIENTO (trámite TRPROC)', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Desbloquear procedimiento transformación. (Caso 6.4)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT-Desbloqueo', enlaces:''},
  {caso:'7', desc:'Error Netflix - Error al asignar procedimiento', clase:'NUEVO ADRIANO', tipo:'Escritorio Judicial', cat:'Error al asignar procedimientos (Caso 7)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'EJ-Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/bord3uRwm5LnDQeWfANgmN'},
  {caso:'8', desc:'NORMAS DE REPARTO EQUILIBRADO DE CARGAS Y/O ELIMINAR COMPENSACIONES | Poner y quitar exenciones, reparto aleatorio', clase:'NUEVO ADRIANO', tipo:'Normas de Reparto', cat:'- (Caso 8)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'Cargas y normas de Reparto', enlaces:''},
  {caso:'9', desc:'PROVEER ESCRITOS (DE TRÁMITE)', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error al proveer escritos (Caso 9)', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/4w1Rn6nbJtQLUHtvWwvZRV'},
  {caso:'10', desc:'No se puede devolver un recurso RREC', clase:'nUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error devolucion recurso (Caso 10)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'11', desc:'Configuración nuevas voces tablas maestras en adaptación a NT CTEAJE', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Consulta/configurac. concepto procesal (Caso 11)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Configuración concepto procesal', enlaces:''},
  {caso:'12', desc:'Organos adscritos SCNE', clase:'NUEVO ADRIANO', tipo:'SCNE', cat:'Adscripción Órgano (Caso 12)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'SCNE', enlaces:''},
  {caso:'13', desc:'Motor Tramitación (residual)', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'-', grupoPre:'', nivelCSU:'MT- Otros', agrupacion:'', enlaces:''},
  {caso:'14', desc:'Caso AsuntosHistoriaEntity no encontrado', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error timeline (Caso 14)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'15', desc:'Incoación multiple de asunto/Errores en la incoación', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error INCOA (Caso 15)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Numeradores', enlaces:''},
  {caso:'16', desc:'Error en la CONSOLIDACIÓN del EJE', clase:'NUEVO ADRIANO', tipo:'Gestión EJE', cat:'Error en consolidación (Caso 16)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'GEJE- Solución explotación (error)', enlaces:''},
  {caso:'17', desc:'No puede realizar IREC/ cuestiones sobre elevación actuaciones por recurso apelación', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error al elevar recurso (Caso 17)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/hjd5ZxcGCENqVoPSwnnSxU; https://videos.justicia.junta-andalucia.es/w/kyjTSp1e13Y4D8Q6gUcc1x; https://videos.justicia.junta-andalucia.es/w/in7EPtr687vxz62AUFbkef; https://videos.justicia.junta-andalucia.es/w/hjd5ZxcGCENqVoPSwnnSxU; https://videos.justicia.junta-andalucia.es/w/kyjTSp1e13Y4D8Q6gUcc1x; https://videos.justicia.junta-andalucia.es/w/in7EPtr687vxz62AUFbkef'},
  {caso:'18', desc:'Eliminar procedimiento creado por error por el usuario y liberacion de numerador.', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error usuario (Caso 18)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error usuarIo)', enlaces:''},
  {caso:'19', desc:'No reciben atestados de determinados organismos', clase:'NUEVO ADRIANO', tipo:'Integración Lexnet', cat:'Error incorporación atestados Lexnet (Caso 19)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error usuarIo)', enlaces:'https://videos.justicia.junta-andalucia.es/w/skAUxXzqowHxnSwQWRCxag; https://videos.justicia.junta-andalucia.es/w/5xutwHVpoAbdjNJ7m7udyY'},
  {caso:'20', desc:'Ocultar visibilidad de documentos sensibles', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error de visibilidad asuntos (Caso 20)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'21', desc:'Finalizar o eliminar un tramite en ejecución', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error en trámite en ejecución (Caso 21)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/eKe4YKS6EgmysUp8w4bAs4'},
  {caso:'22', desc:'No se puede realizar TRPROC', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error transformación TRPROC (Caso 22)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/1G7m99pYxt6cgtoRJbDviQ'},
  {caso:'23', desc:'Rechazar escrito pendiente de aceptar', clase:'NUEVO ADRIANO', tipo:'Escritorio judicial', cat:'Rechazar escrito pendiente de aceptar (Caso 23)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'EJ-Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/5NkxeSgfd6P8CWGAQ2iskg'},
  {caso:'24', desc:'Acumulaciones', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error en la acumulación (Caso 24)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/o4FeUW66VauRB8eHdqFz1r'},
  {caso:'25', desc:'Asunto no pertenece al órgano (ASUNTOS ANTIGUOS)', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error acceso al procedimiento (Caso 25)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'26', desc:'Cambiar estado documento de pendiente firma a cancelado', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Modificacion estado del documento (Caso 26)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'27', desc:'Error visor EJE al asignar procedimiento', clase:'NUEVO ADRIANO', tipo:'Escritorio judicial', cat:'Error visor EJE al asignar procedimiento (Caso 27)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'EJ-Solución explotación (error)', enlaces:''},
  {caso:'28', desc:'Desconsignar diligencias SCNE', clase:'NUEVO ADRIANO', tipo:'SCNE', cat:'Desconsignacion de diligencias (Caso 28)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'SCNE', enlaces:''},
  {caso:'29', desc:'Cambio de un Asunto mover bandeja de entrada de civil a penal', clase:'NUEVO ADRIANO', tipo:'Escritorio judicial', cat:'Cambio jurisdiccion asunto (Caso 29)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'EJ-Solución explotación (error)', enlaces:''},
  {caso:'30', desc:'Caso de itinerado pendiente de una reserva', clase:'NUEVO ADRIANO', tipo:'Agenda Programada', cat:'Reserva de salas (Caso 30)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'AP- Solución explotación Agenda', enlaces:''},
  {caso:'31', desc:'Poner asuntos en bandeja de entrada', clase:'NUEVO ADRIANO', tipo:'Escritorio judicial', cat:'Error usuario (Caso 31)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'EJ- Solución explotación (error usuario)', enlaces:''},
  {caso:'32', desc:'', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Secreto de sumario (Caso 32)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/5fy42tjnLWiPMxqMuzP1op'},
  {caso:'33', desc:'Error ITINE', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error en ficha ITINE (Caso 33)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/pS4eHdyQhEAuMRQb6eddeD'},
  {caso:'34', desc:'Modificar tipo de asunto a EJECUCION', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Modificar tipo asunto (Caso 34)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'35', desc:'Error visualización/descargas documentos', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Error visualización documentos (Caso 35)', grupoPre:'S', nivelCSU:'Servicios Adriano', agrupacion:'ED- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/3u3r3qjornQfHed3tZFPRG'},
  {caso:'36', desc:'Asignación de esquema: procedimientos vigentes/no vigentes', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Modelado trámite-Procesal (Caso 36)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Modelado trámite', enlaces:''},
  {caso:'37', desc:'Documento firmado aparece como borrador', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Error en documentos firmados (Caso 37)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'ED- Solución explotación (error)', enlaces:''},
  {caso:'38', desc:'No puede aceptar asunto: no se encuentra origen de la itineración', clase:'NUEVO ADRIANO', tipo:'Escritorio judicial', cat:'Error al aceptar asuntos (Caso 38)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'EJ- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/bord3uRwm5LnDQeWfANgmN'},
  {caso:'39', desc:'No funciona TACC', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error trámite TACC (Caso 39)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'40', desc:'Error SIJE/DEVSIJE', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error SIJE (Caso 40)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'41', desc:'Cambiar NIG', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Modificación NIG (Caso 41)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'42', desc:'Error envío a firma (crear documento) VISOR', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error envío a firma (crear documento) (Caso 42)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/4sGqjGvCheqduBVZ2SsvVN'},
  {caso:'43', desc:'Error al aceptar escrito', clase:'NUEVO ADRIANO', tipo:'Escritorio judicial', cat:'', grupoPre:'', nivelCSU:'Servicios Basal Adriano/Servicios Adriano |  |', agrupacion:'EJ- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/5NkxeSgfd6P8CWGAQ2iskg'},
  {caso:'44', desc:'No pueden editar interviniente', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error edición interviniente (Caso 44)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'45', desc:'Cambiar estado recurso a resuelto', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Modificar estado recurso (Caso 45)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'46', desc:'Error envío documento a firma', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error de envío a firma (Caso 46)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'47', desc:'Asignar UPAD en NOJ', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error asignación UPAD en ejecución (Caso 47)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'48', desc:'Error al buscar documentos', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Error al buscar documentos (caso 48)', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'ED- Solución explotación (error)', enlaces:''},
  {caso:'49', desc:'No se vuelcan datos procedimiento o se vuelcan datos incorrectos en plantilla. Al elaborar un documento, la cabecera muestra el tipo/nº procedimiento del que dimana, no el actual.', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Error emisión documentos (Caso 49)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'ED- Solución explotación (error)', enlaces:''},
  {caso:'50', desc:'Plantillas/Modelos Adriano', clase:'NUEVO ADRIANO', tipo:'Gestor Plantillas - Modelos', cat:'Consulta modelos (Caso 50)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'GP- Modelos', enlaces:''},
  {caso:'51', desc:'Habilitar Sala', clase:'NUEVO ADRIANO', tipo:'', cat:'Configurar Salas. OJADE (Caso 51)', grupoPre:'Desarrollo', nivelCSU:'Servicios Basal Adriano', agrupacion:'GA- Salas de Vistas', enlaces:''},
  {caso:'52', desc:'Modelador trámites: poner trámites opcionales', clase:'NUEVO ADRIANO', tipo:'Herramienta Modelado - Flujos', cat:'-', grupoPre:'Servicios Adriano', nivelCSU:'HM- Flujos modelado', agrupacion:'', enlaces:''},
  {caso:'53', desc:'Error creación de notas, tareas, plazos y avisos', clase:'NUEVO ADRIANO', tipo:'Agenda Calendario', cat:'Error anotaciones Agenda (Caso 53)', grupoPre:'Servicios Adriano', nivelCSU:'AP- Solución explotación Agenda', agrupacion:'', enlaces:''},
  {caso:'54', desc:'Error al consultar agenda', clase:'NUEVO ADRIANO', tipo:'Agenda Programada', cat:'Error consulta Agenda (Caso 54)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'AP- Solución explotación Agenda', enlaces:''},
  {caso:'55', desc:'No se puede incorporar un expediente administrativo', clase:'NUEVO ADRIANO', tipo:'Cargador Expedientes', cat:'-', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'Integraciones', enlaces:''},
  {caso:'56', desc:'Al intentar abrir documento emitido muestra mensaje "Este documento no ha sido generado desde compositor de documento".', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Error consulta documentos', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'ED- Solución explotación (error)', enlaces:''},
  {caso:'57', desc:'No se puede abrir escrito/s recibido/s. O al consultar cualquier documento de cualquier asunto, aparece un símbolo de prohibido.', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Error editar documentos', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'ED- Solución explotación (error)', enlaces:''},
  {caso:'58', desc:'No aparecen todas las funcionalidades que el perfil del usuario debe ofrecer en adriano /Opciones Menú', clase:'NUEVO ADRIANO', tipo:'Gestión y Administración', cat:'Configuración', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'GA- Configuración usuarios', enlaces:''},
  {caso:'59', desc:'Error al incorporar Altobex', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error al incorporar Altobex', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/1wAt89EGvrQ4L9J1ufbizX: https://videos.justicia.junta-andalucia.es/w/jf7TaF4kiQQZUCAALwYWQy'},
  {caso:'60', desc:'Registro de Ejecutorias (varios): eliminar/ modificar/ reajustar número de ejecutoria.', clase:'NUEVO ADRIANO', tipo:'Ejecutorias', cat:'Error registro ejecutoria (Caso 60)', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'MT- Numeradores (si pide eliminar ejecutoria, es error usuario)', enlaces:''},
  {caso:'61', desc:'Modificar tipo de asunto de pieza separada a ejecutoria', clase:'NUEVO ADRIANO', tipo:'Ejecutorias', cat:'Modificar tipo asunto a ejecuión (Caso 61)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Numeradores', enlaces:''},
  {caso:'62', desc:'Alta sustitución', clase:'NUEVO ADRIANO', tipo:'Gestión y Administración', cat:'Alta sustitución (Caso 62)', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'GA- Configuración usuarios', enlaces:''},
  {caso:'63', desc:'Error al registrar asuntos', clase:'NUEVO ADRIANO', tipo:'Escritorio judicial', cat:'Error al registrar asuntos (caso 63)', grupoPre:'', nivelCSU:'Servicios Adriano/Procesal', agrupacion:'', enlaces:'https://videos.justicia.junta-andalucia.es/w/a84UVD9Gthd1zn56yNTr9s; https://videos.justicia.junta-andalucia.es/w/qAPgPB9w8T31jzwbQzVZLA; https://videos.justicia.junta-andalucia.es/w/dec66YW6AHK1hakXH9dS6b'},
  {caso:'64', desc:'Error al sacar estadísticas', clase:'NUEVO ADRIANO', tipo:'Estadísticas e Informes', cat:'-', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'EI- Estadísticas e Informes', enlaces:''},
  {caso:'65', desc:'Error visualización documentos EJE', clase:'NUEVO ADRIANO', tipo:'Gestión EJE', cat:'-', grupoPre:'Desarrollo', nivelCSU:'Servicios Basal Adriano', agrupacion:'GEJE- Solución explotación (error)', enlaces:''},
  {caso:'66', desc:'Error al descargar EJE', clase:'NUEVO ADRIANO', tipo:'Gestión EJE', cat:'Error descarga EJE (Caso 66)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'GEJE- Solución explotación (error)', enlaces:''},
  {caso:'67', desc:'Modificación de correos, teléfonos, dirección del Juzgado', clase:'NUEVO ADRIANO', tipo:'Gestión y Administración', cat:'Modificar datos', grupoPre:'', nivelCSU:'CSU/Servicios DevOps/Servicios Adriano', agrupacion:'GA- Configuración órgano', enlaces:''},
  {caso:'68', desc:'Error al eliminar/ gestionar lotes', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error lotes (Caso 68)', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución explotación (error)', enlaces:''},
  {caso:'69', desc:'No aparecen determinados firmantes', clase:'NUEVO ADRIANO', tipo:'Gestión y Administración', cat:'Permisos de firmantes (Caso 69)', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'GA- Configuración usuarios', enlaces:''},
  {caso:'70', desc:'o', clase:'NUEVO ADRIANO', tipo:'Gestión y Administración', cat:'Error Whitelabel (Caso 70)', grupoPre:'', nivelCSU:'Servicios DevOps', agrupacion:'', enlaces:''},
  {caso:'71', desc:'Solicitud inclusión/modificación plantilla', clase:'NUEVO ADRIANO', tipo:'Gestor Plantillas - Modelos', cat:'-', grupoPre:'Procesal', nivelCSU:'Servicios Adriano', agrupacion:'GP- Modelos', enlaces:''},
  {caso:'72', desc:'Error remisión resoluciones a CENDOJ', clase:'NUEVO ADRIANO', tipo:'Integración Cendoj', cat:'-', grupoPre:'Desarrollo', nivelCSU:'Servicios Basal Adriano', agrupacion:'IC -Solución Explotación (error)', enlaces:''},
  {caso:'73', desc:'Configuración/Activación/Distribución códigos buzones LexNET', clase:'NUEVO ADRIANO', tipo:'Integración Lexnet', cat:'Buzones LexNET (Caso 73)', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'MT- Configuración concepto procesal', enlaces:''},
  {caso:'74', desc:'Error al notificar por NOTLEX', clase:'NUEVO ADRIANO', tipo:'Integración Lexnet', cat:'Error envío Lexnet', grupoPre:'', nivelCSU:'Servicios Adriano', agrupacion:'IL- Solución Explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/ubYKYqX4pPKzKhAM75JozR;'},
  {caso:'75', desc:'No se puede incorporar por trámite Altobex%: problema con el tipo o tamaño del fichero a incorporar', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error fichero no admitido (Altobex) (Caso 75)', grupoPre:'Explotación', nivelCSU:'Servicios Adriano', agrupacion:'MT- Solución Explotación (error)', enlaces:''},
  {caso:'76', desc:'No pueden devolver exhortos por REXH', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error cooperación judicial. EXHORTO', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'MT- Solución Explotación (error)', enlaces:''},
  {caso:'77', desc:'Documentos aparecen cortados al visualizarlos en la pestaña documentos', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Errores en documentos visualizados (Caso 77)', grupoPre:'Desarrollo', nivelCSU:'Servicios Basal Adriano', agrupacion:'ED- Solución explotación (error)', enlaces:''},
  {caso:'78', desc:'Error envío FSAEC/FSAE (firmeza sentencia apertura ejecución)', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Error FSAE/FSAEC (Caso 78)', grupoPre:'No se usa', nivelCSU:'Servicios Adriano', agrupacion:'EJEC- Solución Explotación (error)', enlaces:''},
  {caso:'79', desc:'Error al registrar efecto', clase:'NUEVO ADRIANO', tipo:'Piezas y Depósitos judiciales', cat:'-', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'PD-Solución Explotación (error)', enlaces:''},
  {caso:'80', desc:'Solicitud eliminación de tareas, plazos, avisos o alarmas', clase:'NUEVO ADRIANO', tipo:'Plazos, avisos y alarmas', cat:'-', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'PAA- Solución Explotación (error)', enlaces:'https://videos.justicia.junta-andalucia.es/w/tysHLJuK9r82oY3k9A1Ndm'},
  {caso:'81', desc:'Error al firmar', clase:'NUEVO ADRIANO', tipo:'Portafirmas', cat:'Error al firmar', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'PF- Solución Explotación (error)', enlaces:''},
  {caso:'82', desc:'Errores en migración (no se han migrado documentos, asuntos...)', clase:'NUEVO ADRIANO', tipo:'Procedimientos ETL migración', cat:'Errores en migración', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'ETL-Solución Explotación (error)', enlaces:''},
  {caso:'83', desc:'Error al repartir asunto', clase:'NUEVO ADRIANO', tipo:'Registro y Reparto', cat:'Error al repartir asuntos', grupoPre:'Desarrollo', nivelCSU:'Servicios Adriano', agrupacion:'', enlaces:'https://videos.justicia.junta-andalucia.es/w/57UxjFJXm4kgZiD6KMNMtj'},
  {caso:'84', desc:'Error al registrar asunto en RyR', clase:'NUEVO ADRIANO', tipo:'Registro y Reparto', cat:'Error al registrar asuntos', grupoPre:'', nivelCSU:'Servicios Adriano/Procesal', agrupacion:'', enlaces:'https://videos.justicia.junta-andalucia.es/w/dec66YW6AHK1hakXH9dS6b'},
  {caso:'85', desc:'El usuario intenta eliminar un interviniente y le muestra error: "El Interviniente/Representante ... no se puede eliminar por tener relación con otras entidades"', clase:'NUEVO ADRIANO', tipo:'Motor Tramitación', cat:'Eliminar interviniente', grupoPre:'Explotación', nivelCSU:'Servicios Adriano/Procesal', agrupacion:'', enlaces:''},
  {caso:'86', desc:'Verificación o cotejo de documentos mediante HCV', clase:'NUEVO ADRIANO', tipo:'Editor documentos', cat:'Verificación firma documento (HCV)', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'', enlaces:''},
  {caso:'87', desc:'Lentitud / problema de rendimiento de carga en MACROCAUSA', clase:'NUEVO ADRIANO', tipo:'Lentitud', cat:'Macrocausa', grupoPre:'', nivelCSU:'Servicios Basal Adriano', agrupacion:'', enlaces:''},
];

const ODS_GRUPO = {
    "78":  "No se usa",
    "10":  "Servicios Basal Adriano",
    "63":  "Servicios Adriano/Procesal",
    "6.4":  "Servicios Adriano",
    "30":  "Servicios Basal Adriano",
    "87":  "Servicios Basal Adriano",
    "49":  "Servicios Adriano",
    "62":  "Servicios DevOps",
    "22":  "Servicios Adriano",
    "13":  "MT- Otros",
    "47":  "Servicios Adriano",
    "71":  "Procesal",
    "77":  "Desarrollo",
    "6.2":  "Servicios DevOps",
    "6.1":  "Servicios DevOps (si han ejecutado DACU en padre y sigue bloqueado)",
    "8":  "Servicios Adriano",
    "12":  "Servicios Basal Adriano",
    "65":  "Desarrollo",
    "40":  "Servicios Adriano",
    "14":  "Servicios Basal Adriano",
    "26":  "Servicios Adriano",
    "17":  "Servicios Adriano",
    "28":  "Servicios Adriano",
    "6.3":  "Servicios Adriano",
    "76":  "Servicios Basal Adriano",
    "36":  "Servicios Adriano",
    "4":  "Servicios Adriano",
    "50":  "Servicios Adriano",
    "45":  "Servicios Adriano",
    "60":  "Desarrollo",
    "38":  "Servicios Basal Adriano",
    "83":  "Desarrollo",
    "85":  "Explotación",
    "82":  "Desarrollo",
    "23":  "Servicios Basal Adriano",
    "51":  "Desarrollo",
    "73":  "Desarrollo",
    "55":  "Servicios Adriano",
    "20":  "Servicios Adriano",
    "59":  "Servicios Adriano",
    "86":  "Servicios Basal Adriano",
    "69":  "Servicios DevOps",
    "54":  "Servicios Adriano",
    "66":  "Servicios Basal Adriano",
    "57":  "Servicios Basal Adriano",
    "43":  "Servicios Basal Adriano/Servicios Adriano |  |",
    "80":  "Desarrollo",
    "35":  "S",
    "41":  "Servicios Adriano",
    "5":  "Formación",
    "34":  "Servicios Adriano",
    "6":  "Servicios Adriano",
    "53":  "Servicios Adriano",
    "44":  "Servicios Adriano",
    "72":  "Desarrollo",
    "11":  "Servicios Adriano",
    "70":  "Servicios DevOps",
    "68":  "Servicios Adriano",
    "1":  "Servicios DevOps",
    "58":  "Servicios DevOps",
    "2":  "Servicios Adriano",
    "2.1":  "Servicios Adriano",
    "33":  "Servicios Adriano",
    "67":  "CSU/Servicios DevOps/Servicios Adriano",
    "27":  "Servicios Basal Adriano",
    "16":  "Servicios Basal Adriano",
    "64":  "Desarrollo",
    "24":  "Servicios Adriano",
    "19":  "Servicios Adriano",
    "29":  "Servicios Adriano",
    "1.1":  "Servicios DevOps",
    "61":  "Servicios Adriano",
    "9":  "Servicios DevOps",
    "74":  "Servicios Adriano",
    "37":  "Servicios Adriano",
    "7":  "Servicios Basal Adriano",
    "52":  "Servicios Adriano",
    "81":  "Desarrollo",
    "39":  "Servicios Adriano",
    "48":  "Desarrollo",
    "21":  "Servicios Basal Adriano",
    "56":  "Servicios Adriano",
    "46":  "Servicios Basal Adriano",
    "75":  "Explotación",
    "79":  "Desarrollo",
    "3":  "Servicios Adriano",
    "32":  "Servicios Adriano",
    "31":  "Servicios Adriano",
    "15":  "Servicios Adriano",
    "25":  "Servicios Basal Adriano",
    "18":  "Servicios Adriano",
    "84":  "Servicios Adriano/Procesal",
    "42":  "Servicios Basal Adriano"
};

const ODS_NIVEL_CSU = {
    "78":  "Servicios Adriano",
    "10":  "Servicios Basal Adriano",
    "63":  "Servicios Adriano/Procesal",
    "6.4":  "Servicios Adriano",
    "30":  "Servicios Basal Adriano",
    "87":  "Servicios Basal Adriano",
    "49":  "Servicios Adriano",
    "62":  "Servicios DevOps",
    "22":  "Servicios Adriano",
    "13":  "MT- Otros",
    "47":  "Servicios Adriano",
    "71":  "Servicios Adriano",
    "77":  "Servicios Basal Adriano",
    "6.2":  "Servicios DevOps",
    "6.1":  "Servicios DevOps (si han ejecutado DACU en padre y sigue bloqueado)",
    "8":  "Servicios Adriano",
    "12":  "Servicios Basal Adriano",
    "65":  "Servicios Basal Adriano",
    "40":  "Servicios Adriano",
    "14":  "Servicios Basal Adriano",
    "26":  "Servicios Adriano",
    "17":  "Servicios Adriano",
    "28":  "Servicios Adriano",
    "6.3":  "Servicios Adriano",
    "76":  "Servicios Basal Adriano",
    "36":  "Servicios Adriano",
    "4":  "Servicios Adriano",
    "50":  "Servicios Adriano",
    "45":  "Servicios Adriano",
    "60":  "Servicios Adriano",
    "38":  "Servicios Basal Adriano",
    "83":  "Servicios Adriano",
    "85":  "Servicios Adriano/Procesal",
    "82":  "Servicios Adriano",
    "23":  "Servicios Basal Adriano",
    "51":  "Servicios Basal Adriano",
    "73":  "Servicios Adriano",
    "55":  "Servicios Adriano",
    "20":  "Servicios Adriano",
    "59":  "Servicios Adriano",
    "86":  "Servicios Basal Adriano",
    "69":  "Servicios DevOps",
    "54":  "Servicios Adriano",
    "66":  "Servicios Basal Adriano",
    "57":  "Servicios Basal Adriano",
    "43":  "Servicios Basal Adriano/Servicios Adriano |  |",
    "80":  "Servicios Adriano",
    "35":  "Servicios Adriano",
    "41":  "Servicios Adriano",
    "5":  "Formación",
    "34":  "Servicios Adriano",
    "6":  "Servicios Adriano",
    "53":  "AP- Solución explotación Agenda",
    "44":  "Servicios Adriano",
    "72":  "Servicios Basal Adriano",
    "11":  "Servicios Adriano",
    "70":  "Servicios DevOps",
    "68":  "Servicios Adriano",
    "1":  "Servicios DevOps",
    "58":  "Servicios DevOps",
    "2":  "Servicios Adriano",
    "2.1":  "Servicios Adriano",
    "33":  "Servicios Adriano",
    "67":  "CSU/Servicios DevOps/Servicios Adriano",
    "27":  "Servicios Basal Adriano",
    "16":  "Servicios Basal Adriano",
    "64":  "Servicios Adriano",
    "24":  "Servicios Adriano",
    "19":  "Servicios Adriano",
    "29":  "Servicios Adriano",
    "1.1":  "Servicios DevOps",
    "61":  "Servicios Adriano",
    "9":  "Servicios DevOps",
    "74":  "Servicios Adriano",
    "37":  "Servicios Adriano",
    "7":  "Servicios Basal Adriano",
    "52":  "HM- Flujos modelado",
    "81":  "Servicios Adriano",
    "39":  "Servicios Adriano",
    "48":  "Servicios Adriano",
    "21":  "Servicios Basal Adriano",
    "56":  "Servicios Adriano",
    "46":  "Servicios Basal Adriano",
    "75":  "Servicios Adriano",
    "79":  "Servicios Adriano",
    "3":  "Servicios Adriano",
    "32":  "Servicios Adriano",
    "31":  "Servicios Adriano",
    "15":  "Servicios Adriano",
    "25":  "Servicios Basal Adriano",
    "18":  "Servicios Adriano",
    "84":  "Servicios Adriano/Procesal",
    "42":  "Servicios Basal Adriano"
};

const ODS_TIPO_CASO = {
    "Integración Cendoj":  [
                               "72"
                           ],
    "\"ADRIANO\"":  [
                        "5"
                    ],
    "Cargador Expedientes":  [
                                 "55"
                             ],
    "Portafirmas":  [
                        "81"
                    ],
    "Agenda Calendario":  [
                              "53"
                          ],
    "Ejecutorias":  [
                        "60",
                        "61"
                    ],
    "Escritorio Judicial":  [
                                "7",
                                "23",
                                "27",
                                "29",
                                "31",
                                "38",
                                "43",
                                "63"
                            ],
    "Gestión EJE":  [
                        "16",
                        "65",
                        "66"
                    ],
    "SCNE":  [
                 "12",
                 "28"
             ],
    "Procedimientos ETL migración":  [
                                         "82"
                                     ],
    "Lentitud":  [
                     "87"
                 ],
    "Gestión y Administración":  [
                                     "58",
                                     "62",
                                     "67",
                                     "69",
                                     "70"
                                 ],
    "Herramienta Modelado - Flujos":  [
                                          "52"
                                      ],
    "Integración Lexnet":  [
                               "19",
                               "73",
                               "74"
                           ],
    "Estadísticas e Informes":  [
                                    "64"
                                ],
    "Registro y Reparto":  [
                               "83",
                               "84"
                           ],
    "Motor Tramitación":  [
                              "1",
                              "1.1",
                              "2",
                              "2.1",
                              "3",
                              "4",
                              "6",
                              "6.1",
                              "6.2",
                              "6.3",
                              "6.4",
                              "9",
                              "10",
                              "11",
                              "13",
                              "14",
                              "15",
                              "17",
                              "18",
                              "20",
                              "21",
                              "22",
                              "24",
                              "25",
                              "26",
                              "32",
                              "33",
                              "34",
                              "36",
                              "39",
                              "40",
                              "41",
                              "42",
                              "44",
                              "45",
                              "46",
                              "47",
                              "59",
                              "68",
                              "75",
                              "76",
                              "78",
                              "85"
                          ],
    "Piezas y Depósitos judiciales":  [
                                          "79"
                                      ],
    "Gestor Plantillas - Modelos":  [
                                        "50",
                                        "71"
                                    ],
    "Agenda Programada":  [
                              "30",
                              "54"
                          ],
    "Normas de Reparto":  [
                              "8"
                          ],
    "Editor documentos":  [
                              "35",
                              "37",
                              "48",
                              "49",
                              "56",
                              "57",
                              "77",
                              "86"
                          ],
    "Plazos, avisos y alarmas":  [
                                     "80"
                                 ]
};

const ODS_STATS = {total:93,generated:'2026-06-23'};
