// wiki_knowledge.js - generated 2026-06-23 14:42
// Source: SSDJ Extranet Wiki
'use strict';

const WIKI_ROUTING = {
  'APLICACIONES':{'ADMINISTRACIÓN IML':'?¿','AGENDA IML':'?¿','ARCONTE':'Nivel 1 / Centro de servicio al usuario','ATENEO (CITA PREVIA)':'Nivel 1 / Centro de servicio al usuario','ESCRITORIO JUDICIAL':'Nivel 1 / Centro de servicio al usuario','EVID (ESCRITORIO VIRTUAL DE INMEDIACIÓN DIGITAL)':'Nivel 1 / Centro de servicio al usuario','FORTUNY (EDOC)':'Nivel 3 / MINISTERIO','GESTIÓN DE HISTORIALES IML':'?¿','GESTOR DE INCIDENCIAS / PETICIONES':'Servicios DevOps','HERMES':'Nivel 1 / Centro de servicio al usuario','NEXO BUROFAX':'Nivel 1 / Centro de servicio al usuario','NUEVA SEDE JUDICIAL ELECTRÓNICA':'Servicios / Nueva sede','ORFILA':'Nivel 3 / MINISTERIO','OTROS':'Nivel 1 / Centro de servicio al usuario','PORTAFIRMASNG':'Servicios DevOps','PORTALES ADRIANO':'Servicios / SACOEP','QUENDA (GESTIÓN DE TURNOS)':'Nivel 1 / Centro de servicio al usuario','REMEDY':'Servicios DevOps','TEMIS':'Servicios DevOps','TEMISWS':'Servicios DevOps','TEXTUALIZACIÓN':'Servicios / Textualización'},
  'GESTIÓN_USUARIOS':{'ALTAS':'Nivel 1 / Centro de Servicio al Usuario','COLECTIVO LEXNET':'Servicios Adriano','HERMES':'Servicios DevOps','JARA':'Servicios DevOps','REMEDY':'Servicios DevOps','TEMIS':'Servicios DevOps'},
  'SISTEMAS_INFRAESTRUCTURA':{'DHCP':'Sistemas GTSW','DNS':'Sistemas GTSW','MONITORIZACIÓN':'Sistemas GTSW','SEGURIDAD':'Sistemas GTSW','SISTEMAS DE ACTIVE DIRECTORY / LDAP':'Sistemas GTSW','SISTEMAS DE ALMACENAMIENTO':'Sistemas GTSB','SISTEMAS DE APLICACIÓN':'Sistemas GTSB','SISTEMAS DE BASE DE DATOS':'Sistemas GTSB','SISTEMAS DE CORREO':'Sistemas GTSB','SISTEMAS DE FICHEROS':'Sistemas GTSW','SISTEMAS DE IMPRESIÓN':'Sistemas GTS8','SISTEMAS DE SALVAGUARDIA':'Sistemas GTSB','SISTEMAS DE VIRTUALIZACIÓN':'Sistemas GTSW','SISTEMAS PROXY':'Sistemas GTSW','SUMINISTRO ELÉCTRICO':'Sistemas GTSW','VLAN':'Sistemas GTSW'}
};

const WIKI_KW = {
  '1':['where','from','select','sentencia','auto','decreto','numerador','numeradores','tabla','solicitan','resoluciones','contienen','cada','dado','pueden','modificar','driano','liberar','sobre','principalmente','aparejado','asociados','plantear','llevan','caso'],
  '1.1':['select','where','from','asunto','siguiente','resoluciones','modificar','asuntos','anterior','para','como','caso','debemos','ello','comprobar','expediente','localizar','podemos','documento','copiamos','procedemos','notificada','tabla','solicitado','otra','actual','sido','clase','numerador','civil'],
  '23':['cadena','instr','substr','procedimiento','where','update','select','devuelve','consulta','ejecutar','from','datos','escrito','primera','then','caso','case','incidencia','ejemplo','correspondientes','asunto','este','para','lpad','null','formato','when','tipo','else','rollback'],
  '6.1':['where','select','siguiente','update','tabla','asuntos','from','acumular','registro','realizamos','campo','para','asunto','order','visor','hacemos','correspondiente','desc','expediente','content','caso','desbloquear','procedimiento','xxxxxxxxx','state','valor','referencia','comprobamos','aparece','binder'],
  '6.2':['where','tabla','procedimiento','select','asuntos','estado','siguiente','update','visor','content','correspondiente','expediente','from','desbloquear','realizado','cambio','hacemos','asunto','peticion','comprobamos','state','caso','referencia','desc','registro','order','campo','afectado','xxxxxxxxx','este'],
  '6.3':['null','where','update','asunto','siguiente','select','tabla','asuntos','registro','caso','from','expediente','reclamante','idmax','para','order','desc','correspondiente','estado','propietario','realizamos','hemos','clase','xxxxxxxxx','itinerado','igual','hacer','desde','fecha','comprobar'],
  '6.4':['where','select','update','siguiente','tabla','procedimiento','original','expediente','transformado','asuntos','from','caso','correspondiente','visor','tipo','asunto','content','desbloquear','hacemos','para','registro','order','realizamos','xxxxxxxxx','registros','desc','comprobamos','anular','trproc','null']
};

const WIKI_DESC = {
  '1':'Caso 1) \r\n\r\n Las resoluciones que llevan aparejado un numerador en @driano son Auto, Sentencia y Decreto.\r\n\r\nLas tipologías de resoluciones se contienen en la tabla TM_RESOLUCION_TIPO: select * from core_owner.tm_resolucion_tipos where id = 1; →Auto select * from core_owner.tm_resolucion_tipos where',
  '1.1':'Caso 1.1) \r\n\r\n - En primer lugar, debemos considerar dos aspectos:\r\n\r\na) Que el número de resolución solicitado a añadir o reemplazar no esté ya asociado a otra resolución anterior. En este caso debemos conocer el id del órgano afectado, para ello podemos utilizar la siguiente select a partir del NI',
  '23':'Caso 23] \r\nPasos: \\\\\r\n1. Localizar en BD el escrito mediante la siguiente query (es necesario conocer el nº de procedimiento, el tipo de procedimiento y el NIG. \\\\ \\\\\r\n\r\nSELECT \u0027UPDATE CORE_OWNER.ESCRITOS_RECIBIDOS SET IND_PROVEIDO = \u0027 || IND_PROVEIDO || \r\n                                           ',
  '6.1':'Caso 6.1) \r\n\r\n Identificación del caso: 1. Se mira en el arbolito NIGS (imagen arriba izquierda) \u003e Debe haber un nig que contiene a otro, se pincha en el nig contenido. 2. Se mira en Timeline (imagen margen derecho) que ponga terminador por Acumulación.  \r\n\r\n  1. Lo primero es instar al usuario a qu',
  '6.2':'Caso 6.2) \r\n\r\n Identificación del caso:\r\n\r\nSe debe mirar en Timeline último tramite aparece - Cambio de estado. OJO: no confundir donde pone Estado: Terminado por transformación (XXX en la imagen), hay que fijarse unicamente en últimos tramites ejecutados.  \r\n\r\n Nota: El cambio a determinados estado',
  '6.3':'Caso 6.3) \r\n\r\n Identificación del caso:\r\n\r\nSe mira en Timeline, debe poner Estado: “Terminado por Inhibición”.  \r\n\r\n 1.- Lo primero es instar al usuario a que solicite el rechazo del expediente al órgano al que se inhibió, se puede conocer la localización del expediente desde la propia aplicación, s',
  '6.4':'Caso 6.4) \r\n\r\n Identificación del caso:\r\n\r\nSe mira en Timeline, debe poner último trámite: TRPROC – Estado: Terminado por transformación.  \r\n\r\n 1.- IMPORTANTE: Los expedientes transformados comparten el mismo idasunto, por lo que no es posible mantener los dos expedientes activos a la vez, por el co'
};

const WIKI_PT_KW = ['trabajo','para','puesto','servicios','unificada','equipos','solo','impresoras','servicio','inventario','existen','peticiones','ordenadores','accesorios','aplicaciones','carpeta','equipo','llamada','entrega','cada','expediente','remedy','contrato','alta','fichero','plantilla','baja','nivel','usuario','necesidades','fijos','equipamiento','color','dentro','perfil','material','donde','proveedor','este','desde','como','nacionales','planificacion','fecha','nuevo','nombre','internos','roaming','datos','franquicia'];

const WIKI_STATS = {routes:43, cases:7, ptKeywords:50, generated:'2026-06-23'};

